export const countryDefaults: Record<string, { currency: string; timezone: string; currencySymbol: string }> = {
  'US': { currency: 'USD', timezone: 'America/New_York', currencySymbol: '$' },
  'CA': { currency: 'CAD', timezone: 'America/Toronto', currencySymbol: 'C$' },
  'GB': { currency: 'GBP', timezone: 'Europe/London', currencySymbol: '£' },
  'DE': { currency: 'EUR', timezone: 'Europe/Berlin', currencySymbol: '€' },
  'FR': { currency: 'EUR', timezone: 'Europe/Paris', currencySymbol: '€' },
  'IT': { currency: 'EUR', timezone: 'Europe/Rome', currencySymbol: '€' },
  'ES': { currency: 'EUR', timezone: 'Europe/Madrid', currencySymbol: '€' },
  'NL': { currency: 'EUR', timezone: 'Europe/Amsterdam', currencySymbol: '€' },
  'AU': { currency: 'AUD', timezone: 'Australia/Sydney', currencySymbol: 'A$' },
  'NZ': { currency: 'NZD', timezone: 'Pacific/Auckland', currencySymbol: 'NZ$' },
  'JP': { currency: 'JPY', timezone: 'Asia/Tokyo', currencySymbol: '¥' },
  'CN': { currency: 'CNY', timezone: 'Asia/Shanghai', currencySymbol: '¥' },
  'IN': { currency: 'INR', timezone: 'Asia/Kolkata', currencySymbol: '₹' },
  'BD': { currency: 'BDT', timezone: 'Asia/Dhaka', currencySymbol: '৳' },
  'PK': { currency: 'PKR', timezone: 'Asia/Karachi', currencySymbol: '₨' },
  'LK': { currency: 'LKR', timezone: 'Asia/Colombo', currencySymbol: '₨' },
  'NP': { currency: 'NPR', timezone: 'Asia/Kathmandu', currencySymbol: '₨' },
  'MM': { currency: 'MMK', timezone: 'Asia/Yangon', currencySymbol: 'K' },
  'KH': { currency: 'KHR', timezone: 'Asia/Phnom_Penh', currencySymbol: '៛' },
  'LA': { currency: 'LAK', timezone: 'Asia/Vientiane', currencySymbol: '₭' },
  'KR': { currency: 'KRW', timezone: 'Asia/Seoul', currencySymbol: '₩' },
  'TW': { currency: 'TWD', timezone: 'Asia/Taipei', currencySymbol: 'NT$' },
  'HK': { currency: 'HKD', timezone: 'Asia/Hong_Kong', currencySymbol: 'HK$' },
  'MO': { currency: 'MOP', timezone: 'Asia/Macau', currencySymbol: 'MOP$' },
  'MN': { currency: 'MNT', timezone: 'Asia/Ulaanbaatar', currencySymbol: '₮' },
  'KZ': { currency: 'KZT', timezone: 'Asia/Almaty', currencySymbol: '₸' },
  'UZ': { currency: 'UZS', timezone: 'Asia/Tashkent', currencySymbol: 'лв' },
  'KG': { currency: 'KGS', timezone: 'Asia/Bishkek', currencySymbol: 'лв' },
  'TJ': { currency: 'TJS', timezone: 'Asia/Dushanbe', currencySymbol: 'ЅМ' },
  'AF': { currency: 'AFN', timezone: 'Asia/Kabul', currencySymbol: '؋' },
  'IR': { currency: 'IRR', timezone: 'Asia/Tehran', currencySymbol: '﷼' },
  'IQ': { currency: 'IQD', timezone: 'Asia/Baghdad', currencySymbol: 'ع.د' },
  'JO': { currency: 'JOD', timezone: 'Asia/Amman', currencySymbol: 'د.ا' },
  'LB': { currency: 'LBP', timezone: 'Asia/Beirut', currencySymbol: 'ل.ل' },
  'SY': { currency: 'SYP', timezone: 'Asia/Damascus', currencySymbol: '£' },
  'YE': { currency: 'YER', timezone: 'Asia/Aden', currencySymbol: '﷼' },
  'OM': { currency: 'OMR', timezone: 'Asia/Muscat', currencySymbol: '﷼' },
  'KW': { currency: 'KWD', timezone: 'Asia/Kuwait', currencySymbol: 'د.ك' },
  'QA': { currency: 'QAR', timezone: 'Asia/Qatar', currencySymbol: '﷼' },
  'BH': { currency: 'BHD', timezone: 'Asia/Bahrain', currencySymbol: '.د.ب' },
  'BR': { currency: 'BRL', timezone: 'America/Sao_Paulo', currencySymbol: 'R$' },
  'MX': { currency: 'MXN', timezone: 'America/Mexico_City', currencySymbol: 'MX$' },
  'AR': { currency: 'ARS', timezone: 'America/Argentina/Buenos_Aires', currencySymbol: '$' },
  'CL': { currency: 'CLP', timezone: 'America/Santiago', currencySymbol: '$' },
  'CO': { currency: 'COP', timezone: 'America/Bogota', currencySymbol: '$' },
  'PE': { currency: 'PEN', timezone: 'America/Lima', currencySymbol: 'S/.' },
  'VE': { currency: 'VES', timezone: 'America/Caracas', currencySymbol: 'Bs' },
  'UY': { currency: 'UYU', timezone: 'America/Montevideo', currencySymbol: '$U' },
  'PY': { currency: 'PYG', timezone: 'America/Asuncion', currencySymbol: 'Gs' },
  'BO': { currency: 'BOB', timezone: 'America/La_Paz', currencySymbol: '$b' },
  'EC': { currency: 'USD', timezone: 'America/Guayaquil', currencySymbol: '$' },
  'RU': { currency: 'RUB', timezone: 'Europe/Moscow', currencySymbol: '₽' },
  'UA': { currency: 'UAH', timezone: 'Europe/Kiev', currencySymbol: '₴' },
  'BY': { currency: 'BYN', timezone: 'Europe/Minsk', currencySymbol: 'Br' },
  'MD': { currency: 'MDL', timezone: 'Europe/Chisinau', currencySymbol: 'L' },
  'RO': { currency: 'RON', timezone: 'Europe/Bucharest', currencySymbol: 'lei' },
  'BG': { currency: 'BGN', timezone: 'Europe/Sofia', currencySymbol: 'лв' },
  'RS': { currency: 'RSD', timezone: 'Europe/Belgrade', currencySymbol: 'Дин.' },
  'HR': { currency: 'EUR', timezone: 'Europe/Zagreb', currencySymbol: '€' },
  'SI': { currency: 'EUR', timezone: 'Europe/Ljubljana', currencySymbol: '€' },
  'SK': { currency: 'EUR', timezone: 'Europe/Bratislava', currencySymbol: '€' },
  'LT': { currency: 'EUR', timezone: 'Europe/Vilnius', currencySymbol: '€' },
  'LV': { currency: 'EUR', timezone: 'Europe/Riga', currencySymbol: '€' },
  'EE': { currency: 'EUR', timezone: 'Europe/Tallinn', currencySymbol: '€' },
  'ZA': { currency: 'ZAR', timezone: 'Africa/Johannesburg', currencySymbol: 'R' },
  'EG': { currency: 'EGP', timezone: 'Africa/Cairo', currencySymbol: 'E£' },
  'NG': { currency: 'NGN', timezone: 'Africa/Lagos', currencySymbol: '₦' },
  'KE': { currency: 'KES', timezone: 'Africa/Nairobi', currencySymbol: 'KSh' },
  'GH': { currency: 'GHS', timezone: 'Africa/Accra', currencySymbol: 'GH¢' },
  'ET': { currency: 'ETB', timezone: 'Africa/Addis_Ababa', currencySymbol: 'Br' },
  'TZ': { currency: 'TZS', timezone: 'Africa/Dar_es_Salaam', currencySymbol: 'TSh' },
  'UG': { currency: 'UGX', timezone: 'Africa/Kampala', currencySymbol: 'USh' },
  'RW': { currency: 'RWF', timezone: 'Africa/Kigali', currencySymbol: 'R₣' },
  'MA': { currency: 'MAD', timezone: 'Africa/Casablanca', currencySymbol: 'د.م.' },
  'DZ': { currency: 'DZD', timezone: 'Africa/Algiers', currencySymbol: 'د.ج' },
  'TN': { currency: 'TND', timezone: 'Africa/Tunis', currencySymbol: 'د.ت' },
  'LY': { currency: 'LYD', timezone: 'Africa/Tripoli', currencySymbol: 'ل.د' },
  'SG': { currency: 'SGD', timezone: 'Asia/Singapore', currencySymbol: 'S$' },
  'MY': { currency: 'MYR', timezone: 'Asia/Kuala_Lumpur', currencySymbol: 'RM' },
  'TH': { currency: 'THB', timezone: 'Asia/Bangkok', currencySymbol: '฿' },
  'PH': { currency: 'PHP', timezone: 'Asia/Manila', currencySymbol: '₱' },
  'ID': { currency: 'IDR', timezone: 'Asia/Jakarta', currencySymbol: 'Rp' },
  'VN': { currency: 'VND', timezone: 'Asia/Ho_Chi_Minh', currencySymbol: '₫' },
  'AE': { currency: 'AED', timezone: 'Asia/Dubai', currencySymbol: 'د.إ' },
  'SA': { currency: 'SAR', timezone: 'Asia/Riyadh', currencySymbol: '﷼' },
  'IL': { currency: 'ILS', timezone: 'Asia/Jerusalem', currencySymbol: '₪' },
  'TR': { currency: 'TRY', timezone: 'Europe/Istanbul', currencySymbol: '₺' },
  'CH': { currency: 'CHF', timezone: 'Europe/Zurich', currencySymbol: 'CHF' },
  'SE': { currency: 'SEK', timezone: 'Europe/Stockholm', currencySymbol: 'kr' },
  'NO': { currency: 'NOK', timezone: 'Europe/Oslo', currencySymbol: 'kr' },
  'DK': { currency: 'DKK', timezone: 'Europe/Copenhagen', currencySymbol: 'kr' },
  'IS': { currency: 'ISK', timezone: 'Atlantic/Reykjavik', currencySymbol: 'kr' },
  'PL': { currency: 'PLN', timezone: 'Europe/Warsaw', currencySymbol: 'zł' },
  'CZ': { currency: 'CZK', timezone: 'Europe/Prague', currencySymbol: 'Kč' },
  'HU': { currency: 'HUF', timezone: 'Europe/Budapest', currencySymbol: 'Ft' },
  'AT': { currency: 'EUR', timezone: 'Europe/Vienna', currencySymbol: '€' },
  'BE': { currency: 'EUR', timezone: 'Europe/Brussels', currencySymbol: '€' },
  'PT': { currency: 'EUR', timezone: 'Europe/Lisbon', currencySymbol: '€' },
  'GR': { currency: 'EUR', timezone: 'Europe/Athens', currencySymbol: '€' },
  'FI': { currency: 'EUR', timezone: 'Europe/Helsinki', currencySymbol: '€' },
  'IE': { currency: 'EUR', timezone: 'Europe/Dublin', currencySymbol: '€' },
  'LU': { currency: 'EUR', timezone: 'Europe/Luxembourg', currencySymbol: '€' },
  'MT': { currency: 'EUR', timezone: 'Europe/Malta', currencySymbol: '€' },
  'CY': { currency: 'EUR', timezone: 'Asia/Nicosia', currencySymbol: '€' },
};

export const countries = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CA', name: 'Canada' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'EE', name: 'Estonia' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LY', name: 'Libya' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macau' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MT', name: 'Malta' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'KR', name: 'South Korea' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
];

export const timezones = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Toronto',
  'America/Vancouver',
  'America/Sao_Paulo',
  'America/Mexico_City',
  'America/Argentina/Buenos_Aires',
  'America/Santiago',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/Montevideo',
  'America/Asuncion',
  'America/La_Paz',
  'America/Guayaquil',
  'Europe/London',
  'Europe/Berlin',
  'Europe/Paris',
  'Europe/Rome',
  'Europe/Madrid',
  'Europe/Amsterdam',
  'Europe/Stockholm',
  'Europe/Oslo',
  'Europe/Copenhagen',
  'Europe/Warsaw',
  'Europe/Prague',
  'Europe/Budapest',
  'Europe/Vienna',
  'Europe/Brussels',
  'Europe/Lisbon',
  'Europe/Athens',
  'Europe/Helsinki',
  'Europe/Dublin',
  'Europe/Zurich',
  'Europe/Istanbul',
  'Europe/Moscow',
  'Europe/Kiev',
  'Europe/Minsk',
  'Europe/Chisinau',
  'Europe/Bucharest',
  'Europe/Sofia',
  'Europe/Belgrade',
  'Europe/Zagreb',
  'Europe/Ljubljana',
  'Europe/Bratislava',
  'Europe/Vilnius',
  'Europe/Riga',
  'Europe/Tallinn',
  'Europe/Luxembourg',
  'Europe/Malta',
  'Atlantic/Reykjavik',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Seoul',
  'Asia/Kolkata',
  'Asia/Dhaka',
  'Asia/Karachi',
  'Asia/Colombo',
  'Asia/Kathmandu',
  'Asia/Yangon',
  'Asia/Phnom_Penh',
  'Asia/Vientiane',
  'Asia/Taipei',
  'Asia/Hong_Kong',
  'Asia/Macau',
  'Asia/Ulaanbaatar',
  'Asia/Almaty',
  'Asia/Tashkent',
  'Asia/Bishkek',
  'Asia/Dushanbe',
  'Asia/Kabul',
  'Asia/Tehran',
  'Asia/Baghdad',
  'Asia/Amman',
  'Asia/Beirut',
  'Asia/Damascus',
  'Asia/Aden',
  'Asia/Muscat',
  'Asia/Kuwait',
  'Asia/Qatar',
  'Asia/Bahrain',
  'Asia/Singapore',
  'Asia/Bangkok',
  'Asia/Manila',
  'Asia/Jakarta',
  'Asia/Ho_Chi_Minh',
  'Asia/Dubai',
  'Asia/Riyadh',
  'Asia/Jerusalem',
  'Asia/Nicosia',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Pacific/Auckland',
  'Africa/Johannesburg',
  'Africa/Cairo',
  'Africa/Lagos',
  'Africa/Nairobi',
  'Africa/Accra',
  'Africa/Addis_Ababa',
  'Africa/Dar_es_Salaam',
  'Africa/Kampala',
  'Africa/Kigali',
  'Africa/Casablanca',
  'Africa/Algiers',
  'Africa/Tunis',
  'Africa/Tripoli',
];

export const currencies = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: '$b' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH¢' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'лв' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'Дин.' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'R₣' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
];